<script type="text/javascript" src="{{ url_for(theme.js) }}/src/scrollspy.js?v={{ theme.version }}"></script>
<script type="text/javascript" src="{{ url_for(theme.js) }}/src/post-details.js?v={{ theme.version }}"></script>

<script id='nodebb-comments-script' async="true", ourl="https://v2mm.tech" ocid="61" blogger='cyang' src="https://v2mm.tech/plugins/nodebb-plugin-blog-comments2/lib/simple-hexo.js"></script>